apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hz5m4jmlg-nodejs 
  janus-idp.io/tekton: hz5m4jmlg-nodejs
  backstage.io/kubernetes-id: hz5m4jmlg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hz5m4jmlg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  