apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hz5m4jmlg-nodejs
  janus-idp.io/tekton: hz5m4jmlg-nodejs
  backstage.io/kubernetes-id: hz5m4jmlg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hz5m4jmlg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
